### ISSUE TITLE
Песня, стоящая на повторе, скробблится только 1 раз

### ISSUE THREAD

**Issue by huston007** [huston007/vk-scrobbler#10]

**Comment by Nureble** [comment]
+++
Нужно бы это исправить и будет все топ

**Comment by huston007** [comment]
@Nureble я поизучал проблему с час и не нашёл очевидного решения, а городить костыли так не хотелось. 
Нужно будет сделать ещё один подход

**Comment by Nureble** [comment]
@huston007 Было бы хорошо ^__^

**Comment by Nureble** [comment]
Ну что там?

**Comment by Nureble** [comment]
хэй?

**Comment by huston007** [comment]
Ну вот опен сорс же. Если очень хочется - можно сделать самому. В противном случае - когда нибудь, возможно, у автора найдётся время и желание это сделать = )

**Comment by Nureble** [comment]
Я б с радостью, но я не шарю в этом... Ну хорошо:) Буду ждать и надеяться

**Comment by huston007** [comment]
Пофикшено в #17
