### ISSUE TITLE
Cannot read property 'insertAdjacentHTML' of null

### ISSUE THREAD

**Issue by PekaFat** [huston007/vk-scrobbler#11]
> vk scrobbler. New ui detected =  true
> indicators.js:109 Uncaught TypeError: Cannot read property 'insertAdjacentHTML' of null`

Получаю такую ошибку в консоле, если захожу сразу в аудиозаписи (свои или группы), пример - http://new.vk.com/audios-784 и соответственно скробллер ничего не скробблит и вообще не загружается.

Если же сначала захожу на свою страницу, а потом кликаю на свои аудио или на Группы - Нужная группа - Аудио группы, то всё ок.

**Comment by huston007** [comment]
Похоже, VK поменял вёрстку в этом месте
