### ISSUE TITLE
Не всегда скроблит треки с новым дизайном.

### ISSUE THREAD

**Issue by Nureble** [huston007/vk-scrobbler#12]
Заметил, что в новом дизайне треки не всегда скроблятся.

Включаю браузер и просто нет иконки скроблинга и трек не скроблится. 
![yznzt4f](https://cloud.githubusercontent.com/assets/19212370/15054227/5bef093a-1317-11e6-9b3c-933b39e04edf.png)
Если перезапустить браузер, то все будет нормально, но через определенное время опять пропадает. 
![default](https://cloud.githubusercontent.com/assets/19212370/15054226/5bee63d6-1317-11e6-8411-8aa64d05cde4.gif)

Браузер Google Chrome.
Кроме Vk Scrobbler расширений для ВК нет.

**Comment by huston007** [comment]
@Nureble давайте разбираться.
1. Происходит ли скроблинг на last.fm фактически, отмечаются ли там проигранные треки?
2. В случае возникновения ошибки, пожалуйста, нажмите F12 (если  используется Windows), откроются утилиты разработчика. Там есть вкладка Console, пришлите пожалуйста её содержимое.

**Comment by Nureble** [comment]
@huston007 
Трек, который видно на 2 скрине в топике, удачно заскроблился.
А те, что проигрываются при обнаруженной проблеме (Отсутствие значка скроблинга) - не скроблятся...
![img](https://cloud.githubusercontent.com/assets/19212370/15074527/8c1c2b4e-13b0-11e6-9d35-08bd18284949.png)


Вот консоль.
Открыл ее на вкладке "Аудиозаписи" при проигрывании трека (При возникновении ошибки)
![img 1](https://cloud.githubusercontent.com/assets/19212370/15074593/d948d160-13b0-11e6-9e2f-4bb9a1d95e11.png)

**Comment by huston007** [comment]
Так, в консоли видно ошибку из #11, её мы поправим.

Про то, что трек фактически не скробблится - это уже интереснее.
У расширения есть фоновый процесс, интересно посмотреть на его логи. Для этого нужно
1. Дождаться повторения проблемы.
2. Открыть chrome://extensions/?id=fddcgfefplodcggebdfbddbmfgmaeeeo
3. Включить режим разработчика (галочка справа вверху)
4. Нажать на background.html
![image](https://cloud.githubusercontent.com/assets/4318513/15082373/0751bddc-13d0-11e6-8e29-da57b794c11b.png)
5. Откроется окно, в нём есть вкладка Console. Пришлите, пожалуйста, её содержимое

**Comment by Nureble** [comment]
@huston007 
![img 4](https://cloud.githubusercontent.com/assets/19212370/15082459/e047f306-13d8-11e6-975f-91bcd94b1482.png)

**Comment by huston007** [comment]
@Nureble похоже, на этот раз у вас все эти песни успешно скробблятся = )

**Comment by Nureble** [comment]
@huston007 
Иконки нет, проблема осталась, треки не скроблятся :(
![img 5](https://cloud.githubusercontent.com/assets/19212370/15082577/81c8c00c-13d9-11e6-9df4-ac09edf4d3f8.png)

**Comment by huston007** [comment]
@Nureble довольно странно.
Давайте посмотрим на сетевые запросы. В том же окне есть вкладка Network. Это окно должно быть открыто в некоторое время, чтобы накопились запросы к last.fm (например, 10 минут).

Когда там будет какое-то количество запросов, кликните там правой кнопкой любой запрос и выберите "Save as HAR with content" (или примерно это, если язык другой). Пришлите получившийся архив, пожалуйста.

**Comment by Nureble** [comment]
@huston007 
![screenshot_9](https://cloud.githubusercontent.com/assets/19212370/15082760/92c67db2-13da-11e6-9228-7be833b44bf2.png)

**Comment by huston007** [comment]
@Nureble нет, это не то. Тут нет запросов к last.fm, возможно вы не подождали какое-то время. Или вы подождали, и в консоли появляются сообщения, а запросы не появляются?

**Comment by Nureble** [comment]
@huston007 не подождал, сейчас попробую послушать музыку. Через 15 минут ровно кину скриншот.

**Comment by Nureble** [comment]
@huston007
[fddcgfefplodcggebdfbddbmfgmaeeeo.zip](https://github.com/huston007/vk-scrobbler/files/252865/fddcgfefplodcggebdfbddbmfgmaeeeo.zip)


Заметил одну интересную вещь.
Перешел на другую вкладку, где еще не пропал значок. 
Включил трек, он успешно заскроблился (отсюда и запрос)
Появилась галочка, что трек заскроблен. 
Перезагружаю страницу и значка уже нет... И скроблинг снова не работает.

**Comment by huston007** [comment]
@Nureble пока не удаётся понять проблему.
Пропадающие иконки это одно, сегодня будет апдейт, который это исправит.
Нескроблящийся трек это другое, пока ничего с этим не понятно. 
Давайте посмотрим, изменится ли что-то с сегодняшним апдейтом (версия 2.0.2)

**Comment by Nureble** [comment]
@huston007 Хорошо, буду ждать. Апдейт пройдет сам?
Я не очень знаю об обновлениях расширений для Google Chrome.

**Comment by huston007** [comment]
@Nureble да, придёт сам.
Вероятно, иконка у вас будет показывать что песня заскробблилась, а на самом деле этого не будет.
Понаблюдайте за фактом появления песен на last.fm, пожалуйста

**Comment by Nureble** [comment]
@huston007 Без проблем, а как мне узнать, что апдейт прошел? Что-бы сразу же начать наблюдать. Или в группе ВК появится пост?

**Comment by Nureble** [comment]
@huston007 После апдейта проблема не появлялась :3 
Теперь еще вопрос, если аудиозапись одна в посте и он закреплен (не обязательно), то она будет воспроизводиться снова и снова, а скроблинг аудиозаписи делается только первый раз...
Можете исправить?
т.е, аудиозапись заскроблилась и стоит галочка, что скроблинг удачно проведен и все, а дальше аудиозапись воспроизводится заново, а галочка остается и скроблинг не идет.

**Comment by stsdc** [comment]
@Nureble #10

**Comment by huston007** [comment]
@Nureble супер!
