### ISSUE TITLE
добавьте аддон на addons.mozilla.org

### ISSUE THREAD

**Issue by f1u77y** [huston007/vk-scrobbler#20]
неудобно руками следить за обновлениями

**Comment by huston007** [comment]
@f1u77y да, мы бы рады, но пока что в магазин не пускают без этого: #18

**Comment by huston007** [comment]
@stsdc тут проблема с Analytics решилась благодаря @f1u77y. Попробуй пожалуйста снова отправить расширение на проверку

**Comment by stsdc** [comment]
Так, уже бегу

**Comment by stsdc** [comment]
Закинул на ревью.

**Comment by stsdc** [comment]
Ожидал на ревью две недели и вот:

>Comments:
>This version didn't pass review because of the following problems:

>1) Sending the full URL to Google Analytics is a violation of the user's privacy and therefore not >allowed. Overall, the information you send to GA needs to be free of any personal information or >strictly opt-in.

>2) This add-on is creating DOM nodes from HTML strings containing potentially unsanitized data, by >assigning to innerHTML, jQuery.html, or through similar means. Aside from being inefficient, this is a >major security risk. For more information, see https://developer.mozilla.org/en/XUL_School/DOM_Building_and_HTML_Insertion . Here are some examples that were discovered:
>blocks/auth/auth.js#L14

>Please remove all unused files.

**Comment by huston007** [comment]
@stsdc ужас, что за appstore они устроили = (

**Comment by stsdc** [comment]
один innerHTML остался, но я при отправке объясню зачем он там.
Осталась только Аналитика @huston007

**Comment by f1u77y** [comment]
на этот раз они больше двух недель отвечают?

**Comment by stsdc** [comment]
Привет, @f1u77y !
Ответ от них я получил вот такой:

> Hello,


>Your add-on, VK scrobbler 2.0.4.2, has been reviewed and did not meet the criteria for being hosted in our gallery.

>Reviewer:
>kiefferbp

>Comments:
>This version didn't pass review because of the following problems:

>1) The previous reviewer's concerns of a custom CSP has not been addressed. I also don't see a good use of it from your code.

>2) The MD5 lib you are using is obfuscated. You should either use the unobfuscated version or provide instructions to obtain the obfuscated code from the unobfuscated version. Also, a direct link to the version of the lib you're using would be nice as well.

>2) You log statements and errors to the console, which is not allowed in production add-ons.

>Also, I may be wrong (as I am a new reviewer) but the amount of tracking you do should ideally be opt-in, even with a privacy policy. It would be nice if you provided the users the choice!

Вот так-то... Я, честно говоря, устал править код для них. Если имеешь немного времени, то можешь этим заняться (было бы круто), а я тогда снова закину его на ревью. 

1. Нужно изучить Content Security Policy: нужен ли он нам? Если нет, то удалить его с `manifest.json`. Иначе нужно обосновать использование
  - [https://developer.chrome.com/extensions/contentSecurityPolicy](CSP Chrome)
  - [https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives](CSP Mozilla)

2. Это я уже сам дам ссылочку на необфусцированный, ну или подключить можно в сборщике

3. Добавить опцию отключения логов (по умолчанию **выключено**)

4. Добавить опцию отключения Google Analytics (по умолчанию **включено**)

**Comment by f1u77y** [comment]
@stsdc 
Итак, пока дела как-то так:
- [ ] Посмотрел на CSP, он там, как я понимаю, нужен был только для GA, но теперь он действительно ну нужен, потому что мы не выполняем сторонние скрипты. Или я что-то недопонял, и он также относится к запросам на какие-то страницы.
- [x] Ок
- [x] Отправил PR
- [x] Отправил PR

**Comment by huston007** [comment]
CSP возможно уже не нужен. Нужно проверить, работает ли скроблинг без него и удалить, если работает.

**Comment by f1u77y** [comment]
> Нужно проверить, работает ли скроблинг без него

бтв он даже с CSP у меня отвалился на лисе. пойду смотреть, что не так.

**Comment by stsdc** [comment]
@f1u77y после удаления Analytics i ws.audioscrobbler.com у меня вроде всё работало

**Comment by f1u77y** [comment]
@stsdc а, это из-за моих измениний что-то отвалилось, отбой

**Comment by stsdc** [comment]
@f1u77y, тогда пусть это будет версия 2.1.0 : мы добавили функционал в виде настроек. 
a вообще приходится добавлять ещё одну цифру изза АМО. Они не разрешают загружать одну и туже версию дважды

**Comment by f1u77y** [comment]
@stsdc да, 2.1.0 правильнее. Однако они правы, что стоит бампать как минимум PATCH: незаметные(а иногда и заметные) для пользователя внутренние изменения есть.

**Comment by huston007** [comment]
Ок, абсолютно согласен, пусть следующая будет 2.1.0

**Comment by stsdc** [comment]
> Hello,
> 
> Your add-on, VK scrobbler 2.1.1, has been reviewed and did not meet the criteria for being hosted in our gallery.
> 
> Reviewer:
> Andreas Wagner
> 
> Comments:
> This version didn't pass review because of the following problems:
> 
> 1) As mentioned before at least some of your GA tracking needs to be opt in, specifically whenever you transmit personal data. In this case, it's your 'scrobbled', 'loved', 'unloved', and 'toggle pause scrobbling' events which contain artist and song names.

**Comment by andrey-skl** [comment]
@stsdc так вроде добавили же галочку для отключения GA, нет?

**Comment by stsdc** [comment]
Да, я ему отвечу.

**Comment by f1u77y** [comment]
@stsdc может, он хочет, чтобы GA по дефолту было выключено? 
Правда, тогда я бы поставил под сомнение нужность: кому из юзеров интересно включать GA?

**Comment by stsdc** [comment]
> Opt-in means it needs to be disabled by default unless explicitly enabled by the user.
> 
> Regards,
> Andreas Wagner

**Comment by andrey-skl** [comment]
@stsdc ну. Ладно, давайте для Firefox её по умолчанию выключать. Главное - только для FF. Нужно прокинуть это дефолтное значение как-то при сборке, чтобы для разных браузеров передавать разное.

**Comment by andrey-skl** [comment]
@stsdc можно пока отправить на ревью версию с захардкоженным отключением аналитики по дефолту.

**Comment by stsdc** [comment]
Закинул. 
А вот пока статистика
![stats](https://cloud.githubusercontent.com/assets/6031763/19168872/5e5e9284-8c12-11e6-966e-939f135331c3.png)

**Comment by alesya-h** [comment]
А можно ссылку на AMO? В поиске на нём по запросу "VK scrobbler" не находит :confused:

**Comment by stsdc** [comment]
@alesguzik [VK Scrobbler](https://addons.mozilla.org/en-US/firefox/addon/vk-scrobbler/) 
пока 98 из 143 в очереди на ревью

**Comment by stsdc** [comment]
Queue Position: 25 of 237 -_-

**Comment by stsdc** [comment]
Hello,

> Your add-on, VK scrobbler 2.1.1.1, has been approved and is now available for download in our gallery at https://addons.mozilla.org/addon/vk-scrobbler/
> 
> Reviewer:
> Andreas Wagner
> 
> Comments:
> Thank you for your contribution.
