### ISSUE TITLE
Redirection error after last.fm auth

### ISSUE THREAD

**Issue by stsdc** [huston007/vk-scrobbler#26]
![capture](https://cloud.githubusercontent.com/assets/6031763/17836488/e95761b0-6794-11e6-99ed-77fcf4aac581.PNG)

**Comment by huston007** [comment]
Как это может произойти, интересно. Я такого не разу не поулчал. Хотелось бы подробный сценарий.

**Comment by stsdc** [comment]
Больше не могу воспроизвести.
