### ISSUE TITLE
Иногда останавливается анимация эквалайзера

### ISSUE THREAD

**Issue by f1u77y** [huston007/vk-scrobbler#29]
Пока замечал сабж только в firefox, сейчас пытаюсь воспроизвести в chrome
**UPD** не заметил проблемы в хроме, попробую копать дальше

**Comment by stsdc** [comment]
У меня есть идея переделать анимацию на svg

**Comment by huston007** [comment]
Зачем?
Если не работает старая-добрая GIF анимация, то SVG лишь добавит проблем. Хотя, конечно, она работает нынче в большинстве браузеров.

**Comment by stsdc** [comment]
У меня она тоже бывает не работает. Ну, может, если svg проблемный, тогда на css сделать анимацию? Среди пользователей есть наверняка дизайнеры, можно какой-нибудь конкурс придумать...

**Comment by huston007** [comment]
А как именно она не работает? Я подозреваю, что проблема скорее с логикой включения-отключения анимации, чем с GIF. Ну не может GIF не работать в 2016 году = D

**Comment by stsdc** [comment]
Не знаю, просто перестает работать :D
Никогда не выключал скроблинг...

**Comment by huston007** [comment]
Тогда полюбому бага в JS : )
Я имел в виду включение-выключение в момент старта и остановки проигрывателя.

**Comment by stsdc** [comment]
Нажал на вкл/выкл скроблинга заработала :p

**Comment by huston007** [comment]
Тем более. Теперь осталось понять, что к этому приводит во время работы.

**Comment by f1u77y** [comment]
**Удалось воспроизвести**
1. Перезагрузить страницу
2. Нажать кнопку Play до того, как загрузится расширение

**Comment by f1u77y** [comment]
@huston007 

> Ну не может GIF не работать в 2016 году = D

Inspect element при воспроизведенном баге показывает, что активна таки гифка, но при этом её воспроизведение полностью остановлено. Кстати, мне ещё кажется, что оно подтормаживает иногда. Может, это проблемы лисы(так и не смог воспроизвести в хроме)?
**UPD** похоже, чтобы воспроизвести, надо загрузить лису(например, открыть много вкладок и пройтись по ним всем по очереди). По крайней мере это действие у меня каждый раз воспроизводит баг.
**UPD2** при смене отрисовщика на cairo при примерно тех же действиях анимация есть, хоть и жутко тормозит. Похоже, проблема действительно в лисе. С логикой в js всё(почти) нормально, так что, видимо, я закрою баг.
