### ISSUE TITLE
Поддержка нового раздела Аудиозаписей

### ISSUE THREAD

**Issue by vitalyavolyn** [huston007/vk-scrobbler#40]
https://vk.com/audio?w=vkmusic

**Comment by andrey-skl** [comment]
Да, я собираюсь заняться на выходных. Спасибо

**Comment by andrey-skl** [comment]
@vitalyavolyn я проверил скробблер с новым разделом – кажется, что всё работает. Известны какие-то проблемы с новым разделом?

**Comment by vitalyavolyn** [comment]
@huston007 не поверите: вчера у меня оно не работало :0
но сейчас все хорошо

чудеса.
