### ISSUE TITLE
Feature Request: libre.fm submission

### ISSUE THREAD

**Issue by eternal-sorrow** [huston007/vk-scrobbler#5]
Please add a possibility to submit tracks to libre.fm instead of (of in addition to) last.fm.

**Comment by stsdc** [comment]
@eternal-sorrow, is this project still developed? Because their API page is empty...

**Comment by eternal-sorrow** [comment]
It's api is the same audioscrobbler api as a last.fm. Just replace api hostname with `turtle.libre.fm` and add possibility to login not with oauth but with login and password and it will work.

**Comment by huston007** [comment]
@eternal-sorrow I've been waiting for any voters here and now it's clear. Excuse me, but this will not be done in this project - i think libre.fm is not needed for 99.9% of VK Scrobbler users.
