### ISSUE TITLE
Нет возможности дать права приложению к last.fm

### ISSUE THREAD

**Issue by DnAp** [huston007/vk-scrobbler#6]
Начальное состояние:
Не залогинен в last.fm
Приложению не разрешен доступ в last.fm.
Приложение не установлено.
Воспроизведение:
Устанавливаем приложение.
Открывается last.fm с просьбой авторизоваться.
Логинимся, смотрим что не работает скроблинг.
Самостоятельно лечится включением и выключением приложения в списке плагинов.
Возможное решение 1 - показывать иконку у трека с ошибкой, при клике пытаться получить права на скроблинг.
Возможное решение 2 - в этом состоянии при клике на значек приложения в статус баре пытаться получить права на скроблинг.

**Comment by huston007** [comment]
> Логинимся, смотрим что не работает скроблинг.

@DnAp Простите, из описания не понятно: а вы перезагружаете вкладку vk.com после установки скробблера?

**Comment by DnAp** [comment]
Да перезагружал.
Проблема в том что last.fm после авторизации не перебрасывает(или не перебрасывал, я сейчас не тестировал) на страницу получения прав для вашего плагина.
В теории если первый раз отказаться от выдачи плагину прав на скроблинг то будет такой-же эффект с необходимостью переустановки приложения.

**Comment by f1u77y** [comment]
@DnAp только что протестил ровно эти действия на версии из master -- всё работает. И отказ от выдачи прав тоже тестил, и у меня он тоже работает. Попробуй на версии из master.

**Comment by DnAp** [comment]
Значит за пол года уже пофиксили=)
