### ISSUE TITLE
Не скробблит 

### ISSUE THREAD

**Issue by mastermaker** [huston007/vk-scrobbler#8]
У меня Google Chrome. Версия 49.0.2623.112 m.

Появляются "гаджеты" от приложения в аудиозаписях, поначалу даже показывалось, что скробблит, но собственно скробблинга не было. Пытался тыкать на лайк аудиозаписи, в надежде, что так может аккаунт хотя бы связан со скррбблером, но и тут ничего не вышло. 

Притом не скробблит как и в старой версии VK, так и собственно в новой его версии.

**Comment by huston007** [comment]
@mastermaker Спасибо за репорт.
Возможно, потерялся токен авторизации. В таком случае должна помочь простая переустановка расширения. Можете попробовать?

**Comment by mastermaker** [comment]
Все заработало, большое спасибо.
